name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}     # Changed from DOCKER_USERNAME
          password: ${{ secrets.DOCKERHUB_TOKEN }}        # Changed from DOCKER_PASSWORD
          registry: docker.io                             # Added explicit registry
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: bingutcs/exp:latest,bingutcs/exp:${{ github.sha }}
