name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check Secret Availability
      run: |
        if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
          echo "✓ DOCKERHUB_USERNAME is available"
        else
          echo "✗ DOCKERHUB_USERNAME is missing"
        fi
        if [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
          echo "✓ DOCKERHUB_TOKEN is available"
        else
          echo "✗ DOCKERHUB_TOKEN is missing"
        fi

    - name: Docker Login
      if: success()
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      if: success()
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: bingutcs/exp:latest
